# Generated by Django 5.0 on 2023-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('observations', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
            ],
        ),
    ]
